### PR TITLE
6

### PR DESCRIPTION
**Pull request by alexmalus**

### CODE REVIEW

**Comment by alexmalus** [comment]
### Issue analysis
#### Getting my phone access to my local chablie
	Started rails like:
	rails s -b 0.0.0.0

	Local IP
	From my linux machine, opened: https://www.whatismyip.com/what-is-my-public-ip-address/
	
	Phone URL
	Constructed the following URL on my phone to access the app:

	http://<Local IP>:3000

### Resolving the issue
	Received pointers:
	Code for search bar can be found here: https://github.com/ribaishtiaq/Chablie/blob/master/app/views/layouts/_header.html.erb
	And the SCSS is here: https://github.com/ribaishtiaq/Chablie/blob/master/app/assets/stylesheets/search.scss

	--

	The header partial was not respecting the Bulma format.
	Changed accordingly.

	Additionally, had to revamp the whole nav to fit the bulma way.

### Testing the issue
	Open the Chablie app on your phone, or resize your browser.
	The navbar is now mobile friendly.

### Developer's insight
	https://www.whatismyip.com/what-is-my-public-ip-address/

	Inspired by https://stackoverflow.com/questions/1889559/git-diff-to-ignore-m
	Received many '^M' characters when doing git diff.
	Had to use:
	git config core.whitespace cr-at-eol

	--

	https://www130.lunapic.com/editor/

	--

	Inspired:
	https://bulma.io/documentation/components/navbar/
	https://bulma.io/documentation/form/input/

**Comment by alexmalus** [comment]
@ribaishtiaq FYI - Saw that there are many more issues that this project faces:

Executing rails test command - has 5 failed test cases
More sections missing mobile friendly responsiveness.
Documentation can be improved.

**Comment by ribaishtiaq** [comment]
Hi @alexmalus , thank you making this PR i will take a look at your changes and if you want you can open new issue to discuss the other issues

**Comment by ribaishtiaq** [comment]
hi @alexmalus , can you please resolve the conflicts so i can merge the PR and can you share a screenshot of the navbar you created because some CSS files are not loading in my local machine

**Comment by alexmalus** [comment]
_can you please resolve the conflicts_

@ribaishtiaq - Done.

Additionally, Screenshots:

Desktop:
New navbar:
new_navbar_desktop

Navbar option menu:
navbar_options_desktop

Phone or tablet:
New navbar:
new_navbar_phone_or_tablet

Navbar option menu:
navbar_options_phone_or_tablet

Sidenote: On focus works OK.

**Comment by ribaishtiaq** [comment]
@alexmalus looks good, Thank you for contributing :),
You can work on rails test issue and documentation if you want to contribute more.

**Pull request merged**
